spring.application.name=expense-tracker

spring.datasource.url=jdbc:postgresql://db.vhuojowamutwkgvrblsq.supabase.co:5432/postgres?sslmode=require&prepareThreshold=0&binaryTransfer=false&preferQueryMode=simple
spring.datasource.username=postgres
spring.datasource.password=rgJcLxKxUVKjNijp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=8f2d9a5b3c7e4f1a9d8c6b2e7f3a1c5d8e4f6a9b3c1d7e5f9a2b4c6d8e1f3a5

# Mail Settings (Example for GMAIL)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ledgerly.info@gmail.com
spring.mail.password=rgzl wqad itsl vxeg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application Settings
app.frontend.url=http://localhost:5173

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.leak-detection-threshold=2000