spring.application.name=expense-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=it is tanmay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=8f2d9a5b3c7e4f1a9d8c6b2e7f3a1c5d8e4f6a9b3c1d7e5f9a2b4c6d8e1f3a5

# Mail Settings (Example for GMAIL)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ledgerly.info@gmail.com
spring.mail.password=qlol bizg gxip hudp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application Settings
app.frontend.url=http://localhost:5173